FONTS_DIR = "assets/fonts"
INPUT_DIR = "input"
OUTPUT_DIR = "output"
VIDEOS_DIR = "assets/videos"

MIN_LENGTH = 5
MAX_LENGTH = 10
BUFFER = 0.2
SILENCE_THRESHOLD = -30

SAMPLE_RATE = 44100

SHORT_WIDTH = 1080
SHORT_HEIGHT = 1920
